### PR TITLE
fix: catch API request fails

### LINKED ISSUE #1009: App crashes if `coingecko` requests fail
I think coingecko is down in India right now and I'm seeing this consistently. 
If I try to send a transaction (lets say using the `provider-test` example), the app crashes. 
The issue is that coingecko returns a 502 with HTML response and we don't catch any of that [here](https://github.com/coral-xyz/backpack/blob/master/packages/recoil/src/atoms/prices.tsx#L166)

Screenshot 2022-10-04 at 11 25 50 PM
Screenshot 2022-10-04 at 11 25 59 PM

This can probably be handled more gracefully

### PR DESCRIPTION
**Pull request by jim4067**
resolves #1009

### CODE REVIEW

File: packages/recoil/src/atoms/prices.tsx [hunk 1]
```diff
@@ -145,15 +145,23 @@ const pricesForIds = selector({
...
+      return new Map(
+        // Transform the response from id -> price data to addresss -> price data
+        Object.keys(json).map((id) => [
+          coingeckoIdToAddressMap.get(id),
+          json[id],
+        ])
+      );
+    } catch (err) {
+      console.error("error querying all Coingecko IDs", err);
+      return;
```
Comment (armaniferrante) [inline packages/recoil/src/atoms/prices.tsx:163]: Should this return `new Map()` instead?

Comment (jim4067) [reply packages/recoil/src/atoms/prices.tsx:163]: It should. Let me fix that.
