### PR TITLE
fix checking versioned transaction status

### LINKED ISSUE #3978: xNFTs do not support checking the status of a versioned transaction
After submitting a versioned transaction and waiting for the confirmation, an error will be thrown and the `window.xnft.solana.sendAndConfirm` promise fails

Screenshot 2023-05-17 at 10 23 56

### PR DESCRIPTION
**Pull request by wentokay**
fixes #3978 

`window.xnft.solana.sendAndConfirm` fails at the confirmation stage because versioned transactions aren't supported in the getParsedTransaction config, this adds support by adding `maxSupportedTransactionVersion: 0`

### CODE REVIEW

File: packages/common/src/solana/background-connection.ts [hunk 1]
```diff
@@ -1010,17 +1013,23 @@ export async function confirmTransaction(
...
+    let tx = await c.getParsedTransaction(txSig, {
+      commitment,
+      maxSupportedTransactionVersion: 0,
+    });
     while (tx === null) {
-      tx = await c.getParsedTransaction(txSig, commitment);
+      tx = await c.getParsedTransaction(txSig, {
+        commitment,
+        maxSupportedTransactionVersion: 0,
+      });
```
Comment (wentokay) [inline packages/common/src/solana/background-connection.ts:1032]: and this is the other part

File: packages/background/src/backend/solana-connection.ts [hunk 2]
```diff
@@ -472,7 +455,8 @@ export class SolanaConnectionBackend {
     );
     return {
       context: {
-        slot: tx.slot,
+        // tx! keeps existing behavior, but it should be tx?
+        slot: tx!.slot,
```
Comment (wentokay) [inline packages/background/src/backend/solana-connection.ts:459]: and this change

Comment (wentokay) [inline packages/background/src/backend/solana-connection.ts:459]: and this change

**Comment by armaniferrante** [comment]
Can we get this in?

**Comment by wentokay** [comment]
I'll do some more manual testing to try and ensure it doesn't introduce regressions, but if you could also quickly glance over it before merging it'd be much appreciated 🙇‍♂️

**Comment by wentokay** [comment]
converted back to draft as this needs a bit more work to support swaps and possibly other transactions

**Comment by wentokay** [comment]
Screenshot 2023-05-31 at 19 36 16

more context, the connection needs the confirmed commitment to be specified, the confirmation commitment preferences screen might cause issues

Screenshot 2023-05-31 at 19 37 41
